// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DynamicFormController from "./dynamic_form_controller"
import MenuController from './menu_controller';

// 新しいコントローラーを追加
application.register("dynamic-form", DynamicFormController)
application.register('menu', MenuController);

export default application
