services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/rails
      - node_modules:/menu_maker/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium
    environment:
      - SELENIUM_DRIVER_URL=http://selenium:4444/wd/hub
    tty: true
    stdin_open: true

  selenium:
    image: seleniarm/standalone-chromium
    platform: linux/arm64
    ports:
      - "4444:4444"

volumes:
  postgres-data:
  node_modules:
  