services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/menu_maker
      - node_modules:/menu_maker/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      tty: true
      stdin_open: true
volumes:
  postgres-data:
  node_modules:
  