name: RSpec Tests

on:

  pull_request:
    branches:
      - main

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          gem install bundler
          bundle install

      - name: Setup database
        run: |
            cp config/database.ci.yml config/database.yml
            bundle exec rails db:create RAILS_ENV=test
            bundle exec rails db:migrate RAILS_ENV=test
    
      - name: Run RSpec
        run: bundle exec rspec
