name: RSpec Tests

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    env:
      SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
      DB_HOST: localhost
      CAPYBARA_SERVER_PORT: 3001

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: menu_maker_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set --local without 'development'
          bundle install --jobs 4 --retry 3

      - name: Setup database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run RSpec
        run: |
          bundle exec rspec

      - name: Show test results
        if: always()
        run: |
          echo "RSpec tests completed"
