name: RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: menu_maker_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set --local without 'development'
          bundle install --jobs 4 --retry 3

      - name: Setup database
        env:
          RAILS_ENV: test
          DB_HOST: postgres  # サービスコンテナのホスト名を指定
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run RSpec
        run: |
          bundle exec rspec

      - name: Show test results
        if: always()  # 成功または失敗にかかわらず、常に実行されるように変更
        run: |
          echo "RSpec tests completed"