name: RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: menu_maker_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.2

      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          bundle exec rails db:create db:schema:load RAILS_ENV=test

      - name: Run RSpec
        run: |
          bundle exec rspec spec/models spec/system

      - name: Show test results
        run: |
          echo "RSpec tests completed successfully"
